_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: ReLU
batch_size:
    value: 64
dense_layer_neurons:
    value: 128
filter_size:
    value: 3
learning_rate:
    value: 0.001
num_conv_layers:
    value: 3
num_filters:
    value: 32
num_workers:
    value: 8
