_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
            "3":
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: ReLU
batch_norm:
    value: true
batch_size:
    value: 32
data_augmentation:
    value: true
dense_layer_neurons:
    value: 64
dropout_rate:
    value: 0.3
filter_size:
    value: 3
input_size:
    value: 128
learning_rate:
    value: 0.001
max_epochs:
    value: 15
num_conv_layers:
    value: 3
num_filters:
    value: 32
subset_fraction:
    value: 0.3
